WANDB_DIR=/tmp/robopianist/ MUJOCO_GL=osmesa XLA_PYTHON_CLIENT_PREALLOCATE=false CUDA_VISIBLE_DEVICES=0 python train-ppo.py \
    --root-dir /tmp/robopianist/rl/ \
    --warmstart-steps 5000 \
    --max-steps 5000000 \
    --discount 0.8 \
    --agent-config.clip_eps 0.2 \
    --agent-config.epochs 10 \
    --agent-config.lr 0.0003 \
    --trim-silence \
    --gravity-compensation \
    --control-timestep 0.05 \
    --n-steps-lookahead 10 \
    --environment-name "RoboPianist-repertoire-150-ArabesqueNo2-v0" \
    --action-reward-observation \
    --primitive-fingertip-collisions \
    --eval-episodes 1 \
    --camera-id "piano/back" \
    --tqdm-bar \
    --mode online \
    --record-dir /home/zhou/videos \
    --reduced-action-space
